### ISSUE TITLE
Remove space on strip

### ISSUE THREAD

**Issue by up73k** [omnidan/node-emoji#100]
.strip method remove space with ® sign.

```js
emoji.strip('MASCOT® Mannheim') // returns  'MASCOTMannheim'
```

Please fix this.

**Comment by Richienb** [comment]
® is being treated as an emoji.

**Comment by lancedikson** [comment]
I guess, the problem is with space — why is it removed and could it be fixed somehow? :)

**Comment by Richienb** [comment]
Spaces after emojis are automatically removed.

Emoji.strip calls the `Emoji.replace` function with the third parameter set to `true`:

https://github.com/omnidan/node-emoji/blob/4004ffe722364249643eccf493d8aea2448da1f2/lib/emoji.js#L300

That third parameter is named `cleanSpaces`:

https://github.com/omnidan/node-emoji/blob/4004ffe722364249643eccf493d8aea2448da1f2/lib/emoji.js#L274

**Comment by lancedikson** [comment]
Thanks 👍 Looks like we could use `Emoji.replace` instead of `strip` :)

**Comment by up73k** [comment]
Thanks!
