### ISSUE TITLE
 🏴󠁧󠁢󠁥󠁮󠁧󠁿  🏴󠁧󠁢󠁳󠁣󠁴󠁿   england, scotland flags are not decoded even if their unicode values are mentioned in emojifile.js

### ISSUE THREAD

**Issue by Dhanraj-Naik** [omnidan/node-emoji#106]
Hi 
i am getting :waving_black_flag: when i add flag-england(🏴󠁧󠁢󠁥󠁮󠁧󠁿) or flag-scotland(🏴󠁧󠁢󠁳󠁣󠁴󠁿) or flag-wales(🏴󠁧󠁢󠁷󠁬󠁳󠁿) when i unemojify.
so again when i do emojify that :waving_black_flag: string, i am getting following output:
OUTPUT: 🏴?????????????????????????.

Why 🏴󠁧󠁢󠁥󠁮󠁧󠁿  🏴󠁧󠁢󠁳󠁣󠁴󠁿 flags are not decoded even if their codes are mentioned in emojifile.js?

Platform: React Native 63.0.+
Node.js v14.15.5
"node-emoji": "1.10.0".

Any suggestions?

**Comment by Dhanraj-Naik** [comment]
i think the issue is with lodash toArray method here which is used inside emoji.js file to unemojify string to array.
![Screenshot 2021-03-06 at 3 42 17 PM](https://user-images.githubusercontent.com/74100008/110203170-8d8bb380-7e92-11eb-859a-e7c0e634f0d5.png)

That is:
_.toArray('🏴󠁧󠁢󠁥󠁮󠁧󠁿');
outputs as:
["🏴", "󠁧", "󠁢", "󠁥", "󠁮", "󠁧", "󠁿"]


Any help here will be much appreciated.
Thank you

**Comment by JoshuaKGoldberg** [comment]
👋 Looks like this behavior was changed -potentially fixed?- when v2 switched to using [`emojilib`](https://github.com/muan/emojilib) (#113):

```js
import * as emoji from "node-emoji";

console.log(emoji.unemojify("🏴󠁧󠁢󠁥󠁮󠁧󠁿"));
```

```plaintext
:england:
``` 

Note that we're also looking at upgrading to emojilib v3 (#132). So I'll close this issue out as no longer relevant. Cheers!
