### ISSUE TITLE
Add support for regional indicators

### ISSUE THREAD

**Issue by networkException** [omnidan/node-emoji#109]
The character making up flag emojis itself are also common to get rendered nowadays, a list of them can be found here https://en.wikipedia.org/wiki/Regional_indicator_symbol#Unicode_block

**Comment by JoshuaKGoldberg** [comment]
👋 new junior maintainer here, picking up old threads - @networkException (or anybody else), is this still of interest to you? And if so, does `node-emoji@v2` fix it for you? #113 switched to using [`emojilib`](https://github.com/muan/emojilib) internally for emojis.

Note also that #132 is in the works to bump to the latest version of `emojilib`.
