### ISSUE TITLE
NPM has v1.11.0 but this repository only has v1.10.0

### ISSUE THREAD

**Issue by Half-Shot** [omnidan/node-emoji#114]
So it's hard to know what's in the latest release, or if it's safe to use?

**Comment by omnidan** [comment]
Yes, it is safe to use. I am sorry, I simply forgot to create the release on github... thanks for reminding me! 😅 

I created the release now so the release notes can be found here: https://github.com/omnidan/node-emoji/releases/tag/v1.11.0

**Comment by Half-Shot** [comment]
Awesome! Thanks!
