### ISSUE TITLE
Directions to use emoji with "-" in their name

### ISSUE THREAD

**Issue by namiskuukkel** [omnidan/node-emoji#116]
I just took a look at emoji.json and saw there are several emojis whose name contains "-" character. Those can't ofcourse be referenced with the syntax the readme points out (eg. emoji.t-rex). You should update the readme to point out you can also reference the emojis with emoji['t-rex'] which enables access to those emojis.

**Comment by omnidan** [comment]
@namiskuukkel thanks for the suggestion! I think in general we should change the readme to use the `emoji['t-rex']` syntax instead. would you be up for doing a PR for that change?

**Comment by JoshuaKGoldberg** [comment]
Resolved by #118 ✅
