### ISSUE TITLE
Strip method doesn’t strip all emoji

### ISSUE THREAD

**Issue by aral** [omnidan/node-emoji#119]
Assuming there are new emoji codepoints that aren’t included. e.g., the following doesn’t get stripped:

```
🙈 See no evil!
```

**Comment by jrejaud** [comment]
I am running into this issue as well.

**Comment by JoshuaKGoldberg** [comment]
The `🙈 See no evil!` case works for me now in v2! 🥳 

```js
import * as emoji from "node-emoji";

console.log(emoji.strip("🙈 See no evil!"));
```

```plaintext
See no evil!
```

✅
