### ISSUE TITLE
Support new emoji

### ISSUE THREAD

**Issue by jackiehluo** [omnidan/node-emoji#12]
Would be great to have the new emoji that have been added! For instance, Slack supports :face_with_thermometer:, :middle_finger:, and a lot of other emoji from the last release.

**Comment by omnidan** [comment]
@jackiehluo aren't they custom emoji though? I think there are some new official ones too, though, like :taco: (which github doesn't even seem to have yet).

**Comment by jackiehluo** [comment]
Nope, not custom! Both of them are on iOS/OS X, too.

Yeah, GitHub is pretty behind on their emoji game... And it looks like Emoji Cheat Sheet is out of date, too. But I think it would be a pretty great addition!

**Comment by omnidan** [comment]
@jackiehluo Ah, well it shouldn't be hard to add those if there is a list of official names.

**Comment by omnidan** [comment]
I published [`1.2.1`](https://github.com/omnidan/node-emoji/releases/tag/v1.2.1) with the new emoji - thanks a lot :grin:

**Comment by jackiehluo** [comment]
Cool, thanks so much!
