### ISSUE TITLE
Provide esm version

### ISSUE THREAD

**Issue by tobiasdiez** [omnidan/node-emoji#123]
With more and more build tools (vite, nuxt, etc) going towards an esm-first build, it would be nice if a proper [esm interface](https://nodejs.org/api/esm.html) could be provided, i.e. transpile and distribute esm version, including correct [export](https://nodejs.org/api/packages.html#conditional-exports) declaration in `package.json`.

**Comment by JoshuaKGoldberg** [comment]
👋 @tobiasdiez I believe this was resolved by #124 and released in `2.0`. Please post back if not!

**Comment by tobiasdiez** [comment]
Nice thanks a lot!
