### ISSUE TITLE
Add in JSDoc comments from DefinitelyTyped pull request

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [omnidan/node-emoji#136]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65502 adds a lot of `/** ... */` JSDoc comments to code, based on this repo's README.md. I ended up not including those comments in #128 so as to not make too many changes to code.

It'd be great to have someone add those JSDoc comments to this repository! Leaving this issue open as a `good first issue` in case someone wants to come along. 😁 

_(also, note that that PR isn't reviewed as of this issue being filed - those JSDoc comments might have mistakes/typos...)

**Comment by Aryan123-rgb** [comment]
Hii, I am interested. Kindly assign this issue to me ?
