### ISSUE TITLE
Really difficult to see emoji list

### ISSUE THREAD

**Issue by mrmayfield** [omnidan/node-emoji#14]
I'm trying to find specific emojis, but how do I find them? Scrolling sideways through the JSON? It's super de duper laggy and really hard to do . Can we have a hosted webpage where they're all listed?

**Comment by mrmayfield** [comment]
Maybe even linking here is better: https://raw.githubusercontent.com/omnidan/node-emoji/master/lib/emoji.json

**Comment by omnidan** [comment]
@mrmayfield I've noticed it's smooth on Chrome Canary. Still not the best way to find emoji - PRs for improving this are welcome :grin: (make sure to automatically generate from the emoji list)

**Comment by mrmayfield** [comment]
Yeah I found the raw to be infinitely easier to search through, I don't know too much about emoji / unicode but perhaps we can get them displayed in the order they are in the Unicode spec? Seems most logical to me, is that how they're displayed in  existing emoji.json file, as according to Unicode order?

**Comment by omnidan** [comment]
@mrmayfield I think they are simply in alphabetical order :wink:
