### ISSUE TITLE
Typescript fix not released

### ISSUE THREAD

**Issue by burakcbdn** [omnidan/node-emoji#141]
I am trying to use this version, but latest typescript fix is not released so I got this error.

`Error [ERR_REQUIRE_ESM]: require() of ES Module`

**Comment by omnidan** [comment]
@burakcbdn we released [2.1.0](https://github.com/omnidan/node-emoji/releases/tag/v2.1.0) yesterday which migrates the whole project to TypeScript and exports the type definitions. it should solve your issue, but please re-open if you're still having issues 😁
