### ISSUE TITLE
strip emoij

### ISSUE THREAD

**Issue by xangel99** [omnidan/node-emoji#17]
strip all emoij on a string for logging readable string

**Comment by omnidan** [comment]
@xangel99 are you talking about stripping emoji (:smile:) or emojicodes (`:smile:`)? What do you mean by "for logging readable string"?

**Comment by xangel99** [comment]
input string: 
       Host: eseaps001 Addr: 10.XX.XX.XX: - :warning: :wavy_dash: :wavy_dash: low disk space

clean string espected:
       Host: eseaps001 Addr: 10.XX.XX.XX: - low disk space

now i using this regular expression to clean the string 
       /[:][a-z_0-9]+[:]/g

**Comment by xangel99** [comment]
the new method will be strip any emojicode present into the string.

**Comment by omnidan** [comment]
@xangel99 Yeah, that makes sense. I would be happy about a PR for this :wink:

**Comment by omnidan** [comment]
@xangel99 I've found something that might be helpful: http://stackoverflow.com/a/10999907/702288

**Comment by smeijer** [comment]
It should now be possible to abuse the `onMissing` and `format` arguments for this.

**Comment by omnidan** [comment]
@smeijer maybe we could provide a `strip` function that passes the onMissing and format arguments accordingly to emojify

**Comment by smeijer** [comment]
Yes, I already thought of this. But let's first finish the open PR's.

**Comment by omnidan** [comment]
implemented in `1.8.1`, let me know if it works fine @xangel99 @smeijer
