### ISSUE TITLE
Feature idea: a cb for emojify which allows to provide an emoji as an image if it is not found in the built-in set

### ISSUE THREAD

**Issue by OrKoN** [omnidan/node-emoji#18]
For example,

```
var emojiMap = {
  ':test:': 'http://....svg',
}
console.log(emoji.emojify('Some :test: text', name => `<img src="${emojiMap[name]}">`))
```

What do you think?

**Comment by omnidan** [comment]
I like that idea 👌  (`name` should probably not contain `:` though, that way you could simply do: `name => name + '.svg'`)

Feel free to send a PR, otherwise I'll look into this in July when I'm available again :wink:

**Comment by OrKoN** [comment]
Thanks
