### ISSUE TITLE
🚀 Feature: Add .only

### ISSUE THREAD

**Issue by botchi09** [omnidan/node-emoji#194]
### Feature Request Checklist

- [x] I am using the latest version of the package
- [x] I have [searched for related issues](https://github.com/omnidan/node-emoji/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

We have emoji.strip, why not a function that does the exact opposite and returns only emojis?

**Comment by JoshuaKGoldberg** [comment]
> Bug Report Checklist

Out of curiosity @botchi09, is there a reason you didn't use the [**🚀 Feature** template](https://github.com/omnidan/node-emoji/issues/new?assignees=&labels=type%3A+feature&projects=&template=03-feature.yml&title=%F0%9F%9A%80+Feature%3A+%3Cshort+description+of+the+feature%3E)? 🙂

**Comment by JoshuaKGoldberg** [comment]
D'oh, you did. I copy & pasta-d it incorrectly. Sorry 😄 filing an issue...

**Comment by JoshuaKGoldberg** [comment]
I'm curious @botchi09: what do you want to use this new function for? Can you provide some more justification as to why it should exist?

**Comment by botchi09** [comment]
> I'm curious @botchi09: what do you want to use this new function for? Can you provide some more justification as to why it should exist?

We already have strip, it seems logical to have the opposite. My use case is exactly that, removing every non-emoji from a string. I suppose the alternative is iterating every character and calling .which on it.
