### ISSUE TITLE
js-emoji is 404

### ISSUE THREAD

**Issue by drj-io** [omnidan/node-emoji#2]
https://github.com/iamcal/js-emoji/blob/master/emoji.js#L164-L1010

is 404

This is where I would get my lists of emoji.  Just thought I'd let you know.

**Comment by omnidan** [comment]
Ah well, that sucks. I'll just update the link to https://github.com/omnidan/node-emoji/blob/master/lib/emoji.json which is where you can get the emoji list that node-emoji uses (it contains the same emoji as js-emoji). It's JSON, but of course you can convert it to any format you need.
