### ISSUE TITLE
Readme Screenshot Incorrect

### ISSUE THREAD

**Issue by shellscape** [omnidan/node-emoji#33]
README.md shows a screenshot from (I'm assuming) an older version. As `emoji.heart` returns `undefined` in the current published version. That would correspond with the API in rest of the README, but the screenshot shows an API which is no longer apparently supported, and since it's displayed first could give off the wrong info.

**Comment by omnidan** [comment]
@shellscape thanks for the hint! nice catch - I didn't even notice that :wink: 

the image is updated now
