### ISSUE TITLE
Is it possible to require particular emoji instead of including whole bundle?

### ISSUE THREAD

**Issue by vitalets** [omnidan/node-emoji#39]
I would like to use particular set of emoji in my project.
So I need something like this:
```js
const coffee = require('node-emoji/coffee');
```

**Comment by omnidan** [comment]
@vitalets unfortunately, this is currently not possible. if this is something you would like to work on, a PR would be very welcome :grin:

**Comment by Richienb** [comment]
In v1, you can do:

```js
const { coffee } = require("node-emoji/lib/emoji.json")
```
