### ISSUE TITLE
Add support for text emoji

### ISSUE THREAD

**Issue by ahanriat** [omnidan/node-emoji#4]
It could be nice to hace support for text emoji such as:
- `:D` -> 😀
- `;)` -> 😉
  etc..

I would like to submit a PR, do you have an idea where to start ?

**Comment by omnidan** [comment]
@ahanriat adding a second argument to `emojify` that enables text -> emoji would probably be a good idea :wink:

**Comment by ahanriat** [comment]
Ok I'll work on that ! :smiley:

**Comment by omnidan** [comment]
@ahanriat any updates on this? :grin:

**Comment by ahanriat** [comment]
Sorry I was busy with my work ^^ I've submitted #5 but there are still some things I would like to improve :wink:

**Comment by omnidan** [comment]
some input for this: https://stackoverflow.com/questions/5862490/how-to-match-emoticons-with-regular-expressions /cc @ahanriat
