### ISSUE TITLE
Facebook :thinking_face: emoji not showing up

### ISSUE THREAD

**Issue by xitij** [omnidan/node-emoji#40]
First of all thanks for the great library. I'm currently using this library in conjunction with Microsoft Botbuilder to create a facebook chat bot. Most of the emojis are working perfectly, however I'm having an issue with the `:thinking_face:` emoji on facebook (skype as well).

Currently my code looks like this:
```
const buttons = [":heart_eyes: Show me more!", ":thinking_face: Something else"]
    .map((button) => emoji.emojify(button););
```
On facebook I'm seeing the following when the buttons are finally displayed:
![facebook button](http://tinyimg.io/i/oWLOYpe.png)
I'm trying to determine if this is a botbuilder issue or if anyone has been able to `:thinking_face:` to work on facebook using node-emoji.

**Comment by omnidan** [comment]
@xitij seems to work fine in node itself, so it's probably not an issue with this library:

```
> node -e "console.log(require('node-emoji').emojify(':thinking_face:'))"
🤔
```

Did you try sending the emoji itself, without using node-emoji?

**Comment by xitij** [comment]
I used the command you sent node in my terminal and I get output, which is promising, but it doesn't look correct:
![img](http://tinyimg.io/i/1Gmwj37.png)
I'm also seeing the same thing on Skype:
![img](http://tinyimg.io/i/am3Yz4y.png)

When I tried to just send the emoji as text through facebook I'm still seeing the same thing:
![img](http://tinyimg.io/i/sWDfjf8.png)

The code used to produce that is simple:
`session.send(emoji.emojify('Test string with :thinking_face:'));`
`session.send()` is a botframework call that sends a message, which can be ignored.

I still believe it could be a problem with `node-emoji` because when I use the command line and Skype I'm seeing the wrong emoji (circle around a "1"). Is it possible the unicode is incorrect? Am I missing something simple?

Thanks

**Comment by xitij** [comment]
So I did some further research and according to [http://unicode.org/emoji/charts/full-emoji-list.html](the unicode emoji guide) everything is cool. It seems that my Chrome browser is having problems displaying that emoji. 

I've tested it on another machine and everything is working fine, so my browser is the issue. 

Thanks for your help, great library.

**Comment by omnidan** [comment]
@xitij I'm glad you figured it out :grin: :ok_hand:
