### ISSUE TITLE
Icons rendering issue

### ISSUE THREAD

**Issue by krishbhattacharyya** [omnidan/node-emoji#42]
Some icons are not rendering properly in my emulator, I have given few of them:
emoji.get(':double_vertical_bar:');
emoji.get(':black_square_for_stop:');
emoji.get(':black_circle_for_record:');

I am trying to make a react native component using this. Got the result but facing this issue.

![screenshot_1496208637](https://cloud.githubusercontent.com/assets/10433734/26617042/8765b318-45f0-11e7-83a9-4bb5b3d79586.png)

**Comment by omnidan** [comment]
@krishbhattacharyya are you sure this issue is related to node-emoji? Can you try rendering the emoji itself (without this library) and see if it works? I think the problem here might be react-native or platform related.

**Comment by krishbhattacharyya** [comment]
@omnidan, Okay I will check this but please need some time, I will try this without react native, actually busy with some urgent tasks. May be you are right. It seems this is the rendering issue.  
You can see the attached image.

![screenshot_1496311024](https://cloud.githubusercontent.com/assets/10433734/26779014/618049fa-4a01-11e7-9e78-4c771e3be4a4.png)

**Comment by omnidan** [comment]
closing this for now (as it does not seem to be a node-emoji related issue), let me know when you found a solution to this :)
