### ISSUE TITLE
How to get category ?

### ISSUE THREAD

**Issue by abdurrahmanekr** [omnidan/node-emoji#43]
[simple-emoji-picker](https://raw.githubusercontent.com/goshakkk/react-native-simple-emoji-picker/master/images/1.png) How can i categorize emojis ? Just like 'People', 'Nature', 'Foods', 'Activity', 'Places', 'Objects', 'Symbols', 'Flags'.

**Comment by omnidan** [comment]
@abdurrahmanekr this is not possible right now. someone would have to manually group all emoji into categories. see https://github.com/omnidan/node-emoji/issues/31 for more information (basically the same issue as this one)

**Comment by abdurrahmanekr** [comment]
Okay, let's continue on #31
