### ISSUE TITLE
Configure to add <span> around emoji?

### ISSUE THREAD

**Issue by scripting** [omnidan/node-emoji#44]
Thanks for doing node-emoji! I use it in the software that generates my blog, http://scripting.com/.

I was wondering if there is a way to configure node-emoji to add a span around each character you generate so I could control the display with CSS. 

I specifically want to bump the font-size on the emoji. 

You can see why in the first item on today's blog. 

http://scripting.com/2017/06/27.html

The cow is too small, but the text is just the right size. I'd set the size of the emoji to 1.1em to make it small bit bigger. 

Again thanks for node-emoji! :smiley_cat:

**Comment by omnidan** [comment]
Maybe we could add a way to customize the emojify function, by passing another function that transforms the emoji further, like this:

```js
emoji.emojify('I :heart: :coffee:!', (emojiCode, emojiName) => '<span>' + emojiCode + '</span>')
```

That way we could even implement more complicated behaviour, like loading emoji as images:

```js
emoji.emojify('I :heart: :coffee:!', (emojiCode, emojiName) => '<img src="' + emojiName + '.png">')
```

It would be great if you could send a PR for this feature :grin:

**Comment by smeijer** [comment]
I've taken the honer to implement this in #48

**Comment by scripting** [comment]
Update: I'm using the feature in my blog now. Thanks! 👍 

http://scripting.com/2017/07/25.html#a101356

**Comment by omnidan** [comment]
@scripting glad to know it works fine :grin: thanks again for the PR, @smeijer !
