### ISSUE TITLE
format behavior

### ISSUE THREAD

**Issue by omnidan** [omnidan/node-emoji#49]
when `null` is specified as `onMissing` and a `format` function is specified, even non-existant emoji are modified. (introduced by #48)

The question here is which behavior we want. I think it's probably better if the formatting only gets applied to existing emoji and the rest are left alone by default (when `onMissing` is not defined).

**Comment by smeijer** [comment]
Aaah, I missed that one. Sorry for that. I'll submit a PR in a moment.

Regarding to the question on what behavior we want. I think you're right about that. The only case I can think of, is that people wan't to still wrap so they can also replace missing emoji's with something of their own. But than again; they should use `onMissing` for that, not `format`. 

So not passing the `missing` trough `format` seems to be right. It was just my misinterpretation of the `onMissing` call.
