### ISSUE TITLE
support skin color modifiers

### ISSUE THREAD

**Issue by highfeed** [omnidan/node-emoji#57]
Hello!

Why don't work this emoji?

https://runkit.com/embed/3gxoc1t1b4pn

**Comment by RekkyRek** [comment]
+1

**Comment by Extracreative** [comment]
+1

**Comment by omnidan** [comment]
@highfeed these emoji are actually two characters: the original emoji + a skin color modifier. Skin color modifiers are not implemented in this library yet. Unfortunately I don't have much time myself right now, but PRs are welcome :grin:
