### ISSUE TITLE
Allow additional Emojis by custom json

### ISSUE THREAD

**Issue by telkomops** [omnidan/node-emoji#63]
🤜 is not being recognized by node-emoji. This is added in 2016.
What would be right process to add this in the emoji.json ?
can i create a custom configuration and provide all missing emoji's in the separate json?
If i clone the module and update the .json,i might miss fixes on node-emoji. What would be the right approach?

**Comment by omnidan** [comment]
@telkomops I think this should work when I release the next version (because #61 got merged). can you check if this emoji is part of the #61 json file?

**Comment by emctackett** [comment]
This emoji, `'right-facing_fist'`, is in the current `emoji.json` file and I am able to use it successfully.  I think we can close this.
