### ISSUE TITLE
How to add custom emoji from png image

### ISSUE THREAD

**Issue by lgaticaq** [omnidan/node-emoji#7]

**Comment by omnidan** [comment]
Emoji are [unicode characters](http://www.unicode.org/emoji/charts/full-emoji-list.html), feel free to add any existing unicode characters [(by following the guide in README.md)](https://github.com/omnidan/node-emoji#adding-new-emoji) or create your own (you'd have to create a custom font with that character and you need to use that font in your application if you want to make use of the new characters). Here is a collection of unicode characters: http://unicode-table.com/en/

So you can't directly convert a png image to a custom emoji for node-emoji, you'd have to make use of a unicode character sequence and a custom font to do that.

I hope this helped you, if you have any further questions feel free to ask :smile:

**Comment by lgaticaq** [comment]
Thanks
