### ISSUE TITLE
Why is node-emoji rendering unexpected � character in console output?

### ISSUE THREAD

**Issue by jakesee** [omnidan/node-emoji#79]
Original question here: https://stackoverflow.com/questions/57543615/why-is-node-emoji-rendering-unexpected-characters-in-console

The following code prints the emojis correctly

> var emoji = require('node-emoji');
> console.log(emoji.get('crossed_fingers'));
> console.log(emoji.get('baby_bottle'));
> console.log(emoji.get('beer'));
> console.log(emoji.get('champagne'));

But one day overnight it just suddenly decided to add the � character

> �🤞
> �🍼
> �🍺
> �🍾

Does anyone know what is causing this problem? I have tested on Visual Studio Code 1.35.1, 1.36.1, 1.37.1. My latest Windows Update is version 1903. There were no other system changes, and this happened on 2 different laptops.

**Comment by Richienb** [comment]
It's probably your terminal font or similar. It can't possibly be to do with the package itself.
