### ISSUE TITLE
Export hash of functions instead of an instance class

### ISSUE THREAD

**Issue by ngryman** [omnidan/node-emoji#8]
Hey, awesome module!

I, and a vast portion of node developers, are used to pick only functions that they need in a module, instead of the whole namespace:
```javascript
var emojify = require('node-emoji').emojify;
```

This obviously fails as `this` is not defined.

Would you mind exporting a hash of functions instead of an instance class? This is an internal singleton anyway, so having a instance does not have a real purpose here. I can provide a PR if you like.

Thanks!

**Comment by omnidan** [comment]
You're totally right - would be nice if you could provide a PR :smile:

**Comment by omnidan** [comment]
@ngryman any updates on this? :grin:

**Comment by ngryman** [comment]
My bad, I didn't have time lately. Will do this now :)

**Comment by omnidan** [comment]
No worries :wink: Looks good to me.
