### ISSUE TITLE
How to add custom emoji in node-emoji

### ISSUE THREAD

**Issue by sanjeevgaut** [omnidan/node-emoji#80]
I need to add custom emojis in node-emoji. i have image in png format and need to use it as emoji in my node project. 

i have seen this article but not understood how i can proceed.
https://github.com/omnidan/node-emoji/issues/7

@node-emoji
Thanks
Sanjeev Gautam

**Comment by omnidan** [comment]
Unfortunately, that is not possible with emoji. Emoji only offer modifiers for skin color, not the color of any emoji. If you wanted to set a different emoji, you would have to modify it in the font used for emoji. Alternatively, you could just use an image.
