### ISSUE TITLE
Allow multiple words to trigger the same emoji

### ISSUE THREAD

**Issue by jackiehluo** [omnidan/node-emoji#9]
A lot of emojis have more commonly used names that are defined on [Emoji Cheat Sheet](http://www.emoji-cheat-sheet.com)! For instance, :+1: is both "+1" and "thumbsup."

**Comment by omnidan** [comment]
@jackiehluo I would make a new `aliases.json` for that, maybe even allow users to define their own aliases. This would only work with `.get()`, of course. I'll probably have a look at it this weekend, but feel free to send a PR and I'll look at it earlier :wink:

**Comment by jackiehluo** [comment]
Hm, wouldn't it be easier to just modify the existing emoji parser to add the full array of names to `emoji.json`? The aliases are standard across the websites that use the :emoji: syntax, and they could define their own aliases by adding them to `emojifile.js`!

**Comment by jackiehluo** [comment]
Just a follow-up, I don't think that the different trigger words are necessarily aliases, either! It looks like the current parser is just pulling the first word by alphabetical order. :smiley:

**Comment by omnidan** [comment]
Yeah, you're right, it's not like you want to define aliases at runtime :wink: Thanks a lot for the PR! Somehow, [your commit](https://github.com/jackiehluo/node-emoji/commit/849196273f7575cfc768e82036159ae6cad08314) is freezing @github for me :open_mouth:

**Comment by omnidan** [comment]
Merged #11 which should fix this.
